### ISSUE TITLE
SSH tunnel cannot be established

### ISSUE THREAD

**Issue by yks0000** [gravitational/teleconsole#27]
Seeing below error very frequently.

$teleconsole
Starting local SSH server on localhost...
Requesting a disposable SSH proxy on as.teleconsole.com for yhsarma...
Checking status of the SSH tunnel...
SSH tunnel cannot be established, please try again.

**Comment by kontsevoy** [comment]
@yks0000 this usually happens when a connection cannot be made. This usually happens when/if:

* Corporate networks block certain connections
* Network latency / speed is not good enough
* Server is overloaded (depends on the region, you're in Asia it seems) or Azure is having network issues.

From the US we never hit `as.xxx` region so we don't see this error, so looks like either the network in the Azure Asian DC we're using is not as reliable as others, or it's your connection.
