### ISSUE TITLE
Teleconsole fails when running against teleport server 2.6.0

### ISSUE THREAD

**Issue by Overbryd** [gravitational/teleconsole#47]
Hi,

for a pair programming endeavour, I setup my own teleport server.

After some time, I could piece everything together.
Now, I tried `teleconsole -s teleport.myserver.com` and it just fails at me.

I looked into the code, and it seems these projects have completely gone out of sync.

Any chance this could be fixed?

I also tried the other branch, but the same problems. The API you are calling from the, for example `GET /api/version` or `POST /api/sessions` does not exist on my teleport server.

**Comment by kontsevoy** [comment]
@Overbryd I am actually struggling with this myself. Teleport has evolved a lot since Teleconsole was released. This use case (teleconsole client + teleport server) cannot possibly work. I am probably going to clean up Teleconsole server instead and add this to the repository, i.e. you'll get your own private server. 

I hope this will work!
(meanwhile I will close this ticket as "not possible").
